 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cvs", type: :request do
  # Cv. As you add validations to Cv, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cv.create! valid_attributes
      get cvs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cv = Cv.create! valid_attributes
      get cv_url(cv)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cv_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cv = Cv.create! valid_attributes
      get edit_cv_url(cv)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cv" do
        expect {
          post cvs_url, params: { cv: valid_attributes }
        }.to change(Cv, :count).by(1)
      end

      it "redirects to the created cv" do
        post cvs_url, params: { cv: valid_attributes }
        expect(response).to redirect_to(cv_url(Cv.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cv" do
        expect {
          post cvs_url, params: { cv: invalid_attributes }
        }.to change(Cv, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cvs_url, params: { cv: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cv" do
        cv = Cv.create! valid_attributes
        patch cv_url(cv), params: { cv: new_attributes }
        cv.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cv" do
        cv = Cv.create! valid_attributes
        patch cv_url(cv), params: { cv: new_attributes }
        cv.reload
        expect(response).to redirect_to(cv_url(cv))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cv = Cv.create! valid_attributes
        patch cv_url(cv), params: { cv: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cv" do
      cv = Cv.create! valid_attributes
      expect {
        delete cv_url(cv)
      }.to change(Cv, :count).by(-1)
    end

    it "redirects to the cvs list" do
      cv = Cv.create! valid_attributes
      delete cv_url(cv)
      expect(response).to redirect_to(cvs_url)
    end
  end
end
