 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/expertises", type: :request do
  # Expertise. As you add validations to Expertise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Expertise.create! valid_attributes
      get expertises_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expertise = Expertise.create! valid_attributes
      get expertise_url(expertise)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expertise_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      expertise = Expertise.create! valid_attributes
      get edit_expertise_url(expertise)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Expertise" do
        expect {
          post expertises_url, params: { expertise: valid_attributes }
        }.to change(Expertise, :count).by(1)
      end

      it "redirects to the created expertise" do
        post expertises_url, params: { expertise: valid_attributes }
        expect(response).to redirect_to(expertise_url(Expertise.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Expertise" do
        expect {
          post expertises_url, params: { expertise: invalid_attributes }
        }.to change(Expertise, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post expertises_url, params: { expertise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested expertise" do
        expertise = Expertise.create! valid_attributes
        patch expertise_url(expertise), params: { expertise: new_attributes }
        expertise.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the expertise" do
        expertise = Expertise.create! valid_attributes
        patch expertise_url(expertise), params: { expertise: new_attributes }
        expertise.reload
        expect(response).to redirect_to(expertise_url(expertise))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        expertise = Expertise.create! valid_attributes
        patch expertise_url(expertise), params: { expertise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expertise" do
      expertise = Expertise.create! valid_attributes
      expect {
        delete expertise_url(expertise)
      }.to change(Expertise, :count).by(-1)
    end

    it "redirects to the expertises list" do
      expertise = Expertise.create! valid_attributes
      delete expertise_url(expertise)
      expect(response).to redirect_to(expertises_url)
    end
  end
end
